services:
  - type: web
    name: fedelabs-fastapi
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HOST
        value: "0.0.0.0"
      - key: RELOAD
        value: "false"
